[book]
title = "kubook"
authors = ["Tiziano Citro", "Daniele De Vinco", "Vittorio Scarano"]
language = "en"

[output.html]
additional-js = ["src/add-toc.js"]

[preprocessor.subsection-numbering]
command = "cargo run --release --manifest-path=../enumeration/Cargo.toml --locked"
