name: Release on Zenodo

on:
  workflow_dispatch:

jobs:
  create-release-and-upload:
    runs-on: ubuntu-latest
    name: Build PDF, create GitHub release, and upload to Zenodo

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build with mdBook
        run: |
          cargo install mdbook
          mdbook build kubook

      - name: Install wkhtmltopdf
        run: |
          sudo apt-get update
          sudo apt-get install -y weasyprint


      - name: Convert print.html to PDF
        run: |
          weasyprint kubook/book/print.html kubook/book/kubernetes-system-design.pdf

      - name: Get current date for release tag
        id: date
        run: echo "date=$(date +'%Y.%m.%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Create GitHub Release and upload PDF
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.date.outputs.date }}
          name: Release ${{ steps.date.outputs.date }}
          files: kubook/book/kubernetes-system-design.pdf
          draft: false
          prerelease: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: pip install requests

      - name: Upload PDF to Zenodo
        env:
          ZENODO_TOKEN: ${{ secrets.ZENODO_TOKEN }}
        run: python utils/upload_to_zenodo_action.py --pdf kubook/book/kubernetes-system-design.pdf --deposition-id 18786215
